name: unhash
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - git
  - google-api-python-client
  - google-auth-httplib2
  - google-auth-oauthlib
  - ipykernel
  - intel-cmplr-lib-rt
  - numpy
  - numba
  - numba-cuda
